CREATE DATABASE SALES

USE SALES

CREATE TABLE PRODUCTS
(
	PROD_ID INT,
	PROD_DESCRIPTION VARCHAR(50),
	PROD_PRICE DECIMAL(18,2),
	PROD_STOCKS INT
)

CREATE TABLE CUSTOMERS
(
	CUST_ID INT,
	CUST_LASTNAME VARCHAR(20),
	CUST_FIRSTNAME VARCHAR(20),
	CUST_MI VARCHAR(10),
	CUST_ADDRESS VARCHAR(20),
	CUST_CONTACT VARCHAR(15)
)


INSERT INTO PRODUCTS VALUES (01,'LAPTOP', 20000,50)
INSERT INTO PRODUCTS VALUES (02,'MOUSE', 350.59,100)
INSERT INTO PRODUCTS VALUES (03,'KEYBOARD', 450.99,60)
INSERT INTO PRODUCTS VALUES (04,'EXTERNAL HARD DRIVE', 5160.23,60)
INSERT INTO PRODUCTS VALUES (05,'SPEAKER', 999.99,20)

INSERT INTO CUSTOMERS VALUES(1,'TAN','ALEX','I.','DAVAO CITY','1234568')
INSERT INTO CUSTOMERS VALUES(2,'SY','SHARON','E.','DAVAO CITY','13543451')
INSERT INTO CUSTOMERS VALUES(3,'UY','AARON','X.','CEBU CITY','68416')
INSERT INTO CUSTOMERS VALUES(4,'WANG','YU','B.','MANDAUE CITY','8745152')
INSERT INTO CUSTOMERS VALUES(5,'TIU','YEAH','A.','TALISAY CITY','965351')

--SUPPLY THE CORRECT SQL STATEMENTS FOR EACH REQUIREMENTS BELOW. 
--WRITE THE STATEMENTS ON YOUR NOTEBOOK... ALWAYS CONSIDER USING <WHERE> COMMAND

--1 Display all records from table PRODUCTS
--2 Display all records from table CUSTOMERSSELECT * FROM CUSTOMERS
--3 Display all records from table PRODUCTS whose PROD_STOCKS is not greater than 20. Copy the output table
--4 Add a new column for table PRODUCTS, named PROD_NAME with data type varchar and data size 50
--5 Change the datatype of column PROD_ID into varchar with size 10
--6 Display all records from table CUSTOMERS whose Middle Initial is I. Copy the output table
--7 Display the id, lastname, firstname and address of customers whose address is Davao City. Copy the output table.
--8 Change the datatype of column CUST_MI into char with size 2.
--9 Change the datatype of column PROD_PRICE into money.
--10 Add a new column to table CUSTOMERS, named Age with datatype int.
--11 Add a new column to table CUSTOMERS, named Birthdate with datatype datetime.
--12 Remove column birthdate from table CUSTOMERS.
--13 Display all records from table PRODUCTS whose stocks is between 50 and 100. Copy output table.
--14 Remove all records from table CUSTOMERS whose address is Davao City.
--15 Remove database SALES


SELECT * FROM PRODUCTS;

SELECT * FROM CUSTOMERS;

SELECT * FROM PRODUCTS WHERE PROD_STOCKS <= 20;

ALTER TABLE PRODUCTS ADD PROD_NAME VARCHAR(50);

ALTER TABLE PRODUCTS ALTER COLUMN PROD_ID VARCHAR(10);

SELECT * FROM CUSTOMERS WHERE CUST_MI LIKE 'I%';

SELECT CUST_ID, CUST_LASTNAME, CUST_FIRSTNAME, CUST_ADDRESS  FROM CUSTOMERS WHERE CUST_ADDRESS LIKE '%Davao City%';

ALTER TABLE CUSTOMERS ALTER COLUMN CUST_MI CHAR(2);

ALTER TABLE PRODUCTS ALTER COLUMN PROD_PRICE MONEY;

ALTER TABLE CUSTOMERS ADD Age INT;

ALTER TABLE CUSTOMERS ADD Birthdate DATETIME;

ALTER TABLE CUSTOMERS DROP COLUMN Birthdate;

SELECT * FROM PRODUCTS WHERE PROD_STOCKS BETWEEN 50 AND 100;

DELETE FROM CUSTOMERS WHERE CUST_ADDRESS LIKE '%Davao City%';

DROP DATABASE SALES;














